import type { SimpleIcon } from "simple-icons";
import {
  si1password,
  siAirtable,
  siAnthropic,
  siApple,
  siAppletv,
  siApplemusic,
  siAsana,
  siAudible,
  siAuth0,
  siAvast,
  siBackblaze,
  siBandcamp,
  siBasecamp,
  siBitbucket,
  siBitdefender,
  siBitwarden,
  siBitwig,
  siBluesky,
  siBose,
  siBrave,
  siBuffer,
  siBuymeacoffee,
  siCalendly,
  siCashapp,
  siCastbox,
  siCastro,
  siCircleci,
  siClaude,
  siClerk,
  siClickup,
  siCloudflare,
  siCloudinary,
  siCoda,
  siCodecademy,
  siCodecov,
  siCoinbase,
  siConfluence,
  siConvex,
  siCoursera,
  siCrunchyroll,
  siCursor,
  siDashlane,
  siDatadog,
  siDavinciresolve,
  siDazn,
  siDeezer,
  siDigitalocean,
  siDiscord,
  siDistrokid,
  siDocker,
  siDoordash,
  siDropbox,
  siDuolingo,
  siEa,
  siElastic,
  siEmby,
  siEpicgames,
  siEvernote,
  siExpressvpn,
  siFacebook,
  siFigma,
  siFirebase,
  siFlydotio,
  siFramer,
  siFubo,
  siGenius,
  siGhost,
  siGithub,
  siGithubcopilot,
  siGitlab,
  siGofundme,
  siGoogleanalytics,
  siGooglecloud,
  siGoogledrive,
  siGooglemaps,
  siGooglemeet,
  siGooglephotos,
  siGoogletranslate,
  siGrafana,
  siGrammarly,
  siHbo,
  siHbomax,
  siHeadspace,
  siHey,
  siHootsuite,
  siHotjar,
  siHubspot,
  siIcloud,
  siIfttt,
  siInsomnia,
  siInstagram,
  siIntercom,
  siJellyfin,
  siJenkins,
  siJetbrains,
  siJira,
  siKaspersky,
  siKeeper,
  siKickstarter,
  siKofi,
  siKubernetes,
  siLastdotfm,
  siLastpass,
  siLinear,
  siLoom,
  siMailchimp,
  siMake,
  siMalwarebytes,
  siMastodon,
  siMcafee,
  siMedium,
  siMega,
  siMiro,
  siMixpanel,
  siMongodb,
  siMullvad,
  siNamecheap,
  siNba,
  siNetflix,
  siNetlify,
  siNewrelic,
  siNginx,
  siNotion,
  siNordvpn,
  siNorton,
  siObsidian,
  siOkcupid,
  siOvercast,
  siPagerduty,
  siPandora,
  siParamountplus,
  siPatreon,
  siPaypal,
  siPeloton,
  siPerplexity,
  siPhilipshue,
  siPlanetscale,
  siPlaystation,
  siPlex,
  siPluralsight,
  siPocketcasts,
  siPosthog,
  siPostman,
  siPrisma,
  siPrivateinternetaccess,
  siProton,
  siProtondrive,
  siProtonmail,
  siProtonvpn,
  siRailway,
  siRedis,
  siRender,
  siReplit,
  siResend,
  siRevolut,
  siRing,
  siRiotgames,
  siRobinhood,
  siRoblox,
  siRoku,
  siSemrush,
  siSentry,
  siSetapp,
  siShazam,
  siShopify,
  siShowtime,
  siSignal,
  siSketch,
  siSkillshare,
  siSnapchat,
  siSnyk,
  siSonos,
  siSoundcloud,
  siSpotify,
  siSquarespace,
  siStackoverflow,
  siStarz,
  siSteam,
  siStrava,
  siStripe,
  siSubstack,
  siSupabase,
  siSurfshark,
  siTailscale,
  siTelegram,
  siTerraform,
  siThreads,
  siTicktick,
  siTidal,
  siTiktok,
  siTinder,
  siTodoist,
  siTorbrowser,
  siTravisci,
  siTrello,
  siTubi,
  siTuta,
  siTwitch,
  siUber,
  siUbereats,
  siUbisoft,
  siUdemy,
  siUpstash,
  siVercel,
  siVivaldi,
  siWebex,
  siWebflow,
  siWetransfer,
  siWhatsapp,
  siWise,
  siWix,
  siWordpress,
  siWyze,
  siX,
  siYoutube,
  siYoutubemusic,
  siYoutubetv,
  siZapier,
  siZendesk,
  siZoom,
  siBox,
  siCoinbase as siCoinbaseIcon,
  siGotomeeting,
} from "simple-icons";

const ICON_ALIASES: Array<[string[], SimpleIcon]> = [
  // ── Entertainment: Video Streaming ────────────────────────
  [["netflix"], siNetflix],
  [["youtube premium"], siYoutube],
  [["youtube tv"], siYoutubetv],
  [["youtube music"], siYoutubemusic],
  [["youtube"], siYoutube],
  [["hbo max"], siHbomax],
  [["hbo"], siHbo],
  [["apple tv+", "apple tv"], siAppletv],
  [["crunchyroll"], siCrunchyroll],
  [["paramount+", "paramount plus"], siParamountplus],
  [["starz"], siStarz],
  [["showtime"], siShowtime],
  [["fubo", "fubotv"], siFubo],
  [["dazn"], siDazn],
  [["plex pass", "plex"], siPlex],
  [["jellyfin"], siJellyfin],
  [["emby"], siEmby],
  [["tubi"], siTubi],
  [["roku"], siRoku],

  // ── Entertainment: Music & Audio ──────────────────────────
  [["spotify"], siSpotify],
  [["apple music"], siApplemusic],
  [["tidal"], siTidal],
  [["deezer"], siDeezer],
  [["soundcloud"], siSoundcloud],
  [["pandora"], siPandora],
  [["audible"], siAudible],
  [["pocket casts", "pocketcasts"], siPocketcasts],
  [["overcast"], siOvercast],
  [["last.fm", "lastfm"], siLastdotfm],
  [["bandcamp"], siBandcamp],
  [["distrokid"], siDistrokid],
  [["castbox"], siCastbox],
  [["castro"], siCastro],
  [["genius"], siGenius],
  [["shazam"], siShazam],

  // ── Entertainment: Gaming ─────────────────────────────────
  [["playstation plus", "playstation"], siPlaystation],
  [["steam"], siSteam],
  [["ea play", "ea sports"], siEa],
  [["ubisoft+", "ubisoft"], siUbisoft],
  [["epic games"], siEpicgames],
  [["riot games"], siRiotgames],
  [["roblox"], siRoblox],

  // ── Entertainment: Social & Content ───────────────────────
  [["x premium", "twitter"], siX],
  [["twitch turbo", "twitch"], siTwitch],
  [["discord nitro", "discord"], siDiscord],
  [["patreon"], siPatreon],
  [["substack"], siSubstack],
  [["instagram"], siInstagram],
  [["snapchat+", "snapchat"], siSnapchat],
  [["tiktok"], siTiktok],
  [["threads"], siThreads],
  [["mastodon"], siMastodon],
  [["bluesky"], siBluesky],
  [["facebook"], siFacebook],

  // ── Productivity: Dev Tools ───────────────────────────────
  [["github copilot"], siGithubcopilot],
  [["github"], siGithub],
  [["gitlab"], siGitlab],
  [["bitbucket"], siBitbucket],
  [["jetbrains"], siJetbrains],
  [["vercel"], siVercel],
  [["netlify"], siNetlify],
  [["railway"], siRailway],
  [["render"], siRender],
  [["fly.io"], siFlydotio],
  [["digitalocean"], siDigitalocean],
  [["google cloud"], siGooglecloud],
  [["supabase"], siSupabase],
  [["firebase"], siFirebase],
  [["planetscale"], siPlanetscale],
  [["upstash"], siUpstash],
  [["mongodb atlas", "mongodb"], siMongodb],
  [["redis cloud", "redis"], siRedis],
  [["convex"], siConvex],
  [["docker"], siDocker],
  [["kubernetes"], siKubernetes],
  [["terraform cloud", "terraform"], siTerraform],
  [["postman"], siPostman],
  [["insomnia"], siInsomnia],
  [["sentry"], siSentry],
  [["datadog"], siDatadog],
  [["new relic", "newrelic"], siNewrelic],
  [["grafana cloud", "grafana"], siGrafana],
  [["pagerduty"], siPagerduty],
  [["circleci"], siCircleci],
  [["travis ci", "travisci"], siTravisci],
  [["codecov"], siCodecov],
  [["snyk"], siSnyk],
  [["auth0"], siAuth0],
  [["clerk"], siClerk],
  [["resend"], siResend],
  [["posthog"], siPosthog],
  [["mixpanel"], siMixpanel],
  [["hotjar"], siHotjar],
  [["cursor"], siCursor],
  [["replit"], siReplit],
  [["prisma"], siPrisma],
  [["jenkins"], siJenkins],
  [["elastic"], siElastic],
  [["cloudinary"], siCloudinary],
  [["nginx"], siNginx],
  [["stack overflow"], siStackoverflow],

  // ── Productivity: AI Tools ────────────────────────────────
  [["claude pro", "claude"], siClaude],
  [["anthropic"], siAnthropic],
  [["perplexity pro", "perplexity"], siPerplexity],
  [["grammarly"], siGrammarly],

  // ── Productivity: Design ──────────────────────────────────
  [["figma"], siFigma],
  [["sketch"], siSketch],
  [["framer"], siFramer],
  [["webflow"], siWebflow],
  [["miro"], siMiro],
  [["loom"], siLoom],
  [["davinci resolve"], siDavinciresolve],

  // ── Productivity: Collaboration & Office ──────────────────
  [["notion"], siNotion],
  [["obsidian sync", "obsidian"], siObsidian],
  [["coda"], siCoda],
  [["zoom"], siZoom],
  [["dropbox"], siDropbox],
  [["evernote"], siEvernote],
  [["todoist pro", "todoist"], siTodoist],
  [["ticktick"], siTicktick],
  [["linear"], siLinear],
  [["asana"], siAsana],
  [["trello"], siTrello],
  [["jira"], siJira],
  [["confluence"], siConfluence],
  [["clickup"], siClickup],
  [["basecamp"], siBasecamp],
  [["airtable"], siAirtable],
  [["calendly"], siCalendly],
  [["google meet"], siGooglemeet],
  [["google drive"], siGoogledrive],
  [["google photos"], siGooglephotos],
  [["google maps"], siGooglemaps],
  [["google translate"], siGoogletranslate],
  [["webex"], siWebex],
  [["gotomeeting"], siGotomeeting],
  [["setapp"], siSetapp],
  [["box"], siBox],
  [["wetransfer"], siWetransfer],

  // ── Productivity: Marketing & Sales ───────────────────────
  [["mailchimp"], siMailchimp],
  [["hubspot"], siHubspot],
  [["stripe"], siStripe],
  [["shopify"], siShopify],
  [["squarespace"], siSquarespace],
  [["wix"], siWix],
  [["wordpress"], siWordpress],
  [["ghost"], siGhost],
  [["buffer"], siBuffer],
  [["hootsuite"], siHootsuite],
  [["semrush"], siSemrush],
  [["google analytics"], siGoogleanalytics],

  // ── Productivity: Automation ──────────────────────────────
  [["zapier"], siZapier],
  [["ifttt"], siIfttt],
  [["make"], siMake],

  // ── Productivity: Customer Support ────────────────────────
  [["intercom"], siIntercom],
  [["zendesk"], siZendesk],

  // ── Utilities: Cloud Storage ──────────────────────────────
  [["icloud+", "icloud"], siIcloud],
  [["mega"], siMega],
  [["proton drive"], siProtondrive],

  // ── Utilities: Password Managers ──────────────────────────
  [["1password"], si1password],
  [["bitwarden"], siBitwarden],
  [["lastpass"], siLastpass],
  [["dashlane"], siDashlane],
  [["keeper"], siKeeper],

  // ── Utilities: VPN & Privacy ──────────────────────────────
  [["nordvpn"], siNordvpn],
  [["expressvpn"], siExpressvpn],
  [["surfshark"], siSurfshark],
  [["protonvpn", "proton vpn"], siProtonvpn],
  [["mullvad vpn", "mullvad"], siMullvad],
  [["private internet access", "pia"], siPrivateinternetaccess],

  // ── Utilities: Email ──────────────────────────────────────
  [["proton mail", "protonmail"], siProtonmail],
  [["tuta mail", "tuta"], siTuta],
  [["hey"], siHey],
  [["proton"], siProton],

  // ── Utilities: Security ───────────────────────────────────
  [["norton 360", "norton"], siNorton],
  [["mcafee"], siMcafee],
  [["kaspersky"], siKaspersky],
  [["bitdefender"], siBitdefender],
  [["malwarebytes"], siMalwarebytes],
  [["avast"], siAvast],

  // ── Utilities: Infrastructure & Smart Home ────────────────
  [["backblaze"], siBackblaze],
  [["cloudflare"], siCloudflare],
  [["namecheap"], siNamecheap],
  [["tailscale"], siTailscale],
  [["ring protect", "ring"], siRing],
  [["wyze cam", "wyze"], siWyze],
  [["philips hue"], siPhilipshue],
  [["sonos"], siSonos],
  [["bose"], siBose],

  // ── Health ────────────────────────────────────────────────
  [["headspace"], siHeadspace],
  [["strava"], siStrava],
  [["peloton"], siPeloton],

  // ── Education ─────────────────────────────────────────────
  [["duolingo super", "duolingo"], siDuolingo],
  [["coursera plus", "coursera"], siCoursera],
  [["udemy"], siUdemy],
  [["skillshare"], siSkillshare],
  [["pluralsight"], siPluralsight],
  [["codecademy pro", "codecademy"], siCodecademy],

  // ── News & Reading ────────────────────────────────────────
  [["medium"], siMedium],

  // ── Lifestyle ─────────────────────────────────────────────
  [["doordash dashpass", "doordash"], siDoordash],
  [["uber one", "uber eats", "uber"], siUber],
  [["tinder"], siTinder],
  [["okcupid"], siOkcupid],
  [["robinhood gold", "robinhood"], siRobinhood],
  [["coinbase one", "coinbase"], siCoinbaseIcon],
  [["paypal"], siPaypal],
  [["wise"], siWise],
  [["revolut"], siRevolut],
  [["nba"], siNba],

  // ── Communication ─────────────────────────────────────────
  [["whatsapp"], siWhatsapp],
  [["telegram premium", "telegram"], siTelegram],
  [["signal"], siSignal],

  // ── Creator & Fundraising ─────────────────────────────────
  [["ko-fi", "kofi"], siKofi],
  [["buy me a coffee", "buymeacoffee"], siBuymeacoffee],
  [["kickstarter"], siKickstarter],
  [["gofundme"], siGofundme],

  // ── Browsers (if subscribed to premium) ───────────────────
  [["brave"], siBrave],
  [["vivaldi"], siVivaldi],
  [["tor browser", "tor"], siTorbrowser],

  // ── Misc brand fallbacks ──────────────────────────────────
  [["apple fitness+", "apple arcade", "apple news+"], siApple],
];

function normalizeName(name: string): string {
  return name.toLowerCase().trim();
}

export function getBrandIcon(name: string): SimpleIcon | undefined {
  const normalized = normalizeName(name);
  for (const [aliases, icon] of ICON_ALIASES) {
    if (aliases.some((alias) => normalized.includes(alias))) {
      return icon;
    }
  }
  return undefined;
}
