import type { SubscriptionCategory } from "./types";

export interface SubscriptionSuggestion {
  name: string;
  category: SubscriptionCategory;
}

const S = (name: string, category: SubscriptionCategory): SubscriptionSuggestion => ({
  name,
  category,
});

export const SUBSCRIPTION_SUGGESTIONS: SubscriptionSuggestion[] = [
  // ── Entertainment: Video Streaming ────────────────────────
  S("Netflix", "entertainment"),
  S("YouTube Premium", "entertainment"),
  S("YouTube TV", "entertainment"),
  S("YouTube Music", "entertainment"),
  S("Disney+", "entertainment"),
  S("HBO Max", "entertainment"),
  S("Hulu", "entertainment"),
  S("Apple TV+", "entertainment"),
  S("Amazon Prime Video", "entertainment"),
  S("Crunchyroll", "entertainment"),
  S("Paramount+", "entertainment"),
  S("Peacock", "entertainment"),
  S("Starz", "entertainment"),
  S("Showtime", "entertainment"),
  S("Fubo", "entertainment"),
  S("DAZN", "entertainment"),
  S("Plex Pass", "entertainment"),
  S("Jellyfin", "entertainment"),
  S("Emby", "entertainment"),
  S("MUBI", "entertainment"),
  S("Shudder", "entertainment"),
  S("BritBox", "entertainment"),
  S("Discovery+", "entertainment"),
  S("ESPN+", "entertainment"),
  S("Sling TV", "entertainment"),
  S("Philo", "entertainment"),
  S("CuriosityStream", "entertainment"),
  S("Tubi", "entertainment"),
  S("Roku Channel", "entertainment"),
  S("Viki", "entertainment"),
  S("Hotstar", "entertainment"),
  S("JioCinema", "entertainment"),
  S("SonyLIV", "entertainment"),
  S("ZEE5", "entertainment"),

  // ── Entertainment: Music & Audio ──────────────────────────
  S("Spotify", "entertainment"),
  S("Apple Music", "entertainment"),
  S("Tidal", "entertainment"),
  S("Deezer", "entertainment"),
  S("SoundCloud Go", "entertainment"),
  S("Pandora", "entertainment"),
  S("Amazon Music", "entertainment"),
  S("Audible", "entertainment"),
  S("Scribd", "entertainment"),
  S("Pocket Casts", "entertainment"),
  S("Overcast Premium", "entertainment"),
  S("SiriusXM", "entertainment"),
  S("Last.fm", "entertainment"),
  S("Bandcamp", "entertainment"),
  S("DistroKid", "entertainment"),

  // ── Entertainment: Gaming ─────────────────────────────────
  S("PlayStation Plus", "entertainment"),
  S("Xbox Game Pass", "entertainment"),
  S("Nintendo Switch Online", "entertainment"),
  S("Steam", "entertainment"),
  S("EA Play", "entertainment"),
  S("Ubisoft+", "entertainment"),
  S("Epic Games Store", "entertainment"),
  S("GeForce NOW", "entertainment"),
  S("Apple Arcade", "entertainment"),
  S("Google Play Pass", "entertainment"),
  S("Humble Bundle", "entertainment"),
  S("Riot Games", "entertainment"),
  S("Roblox Premium", "entertainment"),

  // ── Entertainment: Social & Content ───────────────────────
  S("Twitch Turbo", "entertainment"),
  S("Discord Nitro", "entertainment"),
  S("Patreon", "entertainment"),
  S("Substack", "entertainment"),
  S("Reddit Premium", "entertainment"),
  S("X Premium", "entertainment"),
  S("Instagram", "entertainment"),
  S("Snapchat+", "entertainment"),
  S("TikTok", "entertainment"),
  S("Threads", "entertainment"),
  S("Mastodon", "entertainment"),
  S("Bluesky", "entertainment"),

  // ── Productivity: Dev Tools ───────────────────────────────
  S("GitHub", "productivity"),
  S("GitHub Copilot", "productivity"),
  S("GitLab", "productivity"),
  S("Bitbucket", "productivity"),
  S("JetBrains", "productivity"),
  S("Vercel", "productivity"),
  S("Netlify", "productivity"),
  S("Railway", "productivity"),
  S("Render", "productivity"),
  S("Fly.io", "productivity"),
  S("Heroku", "productivity"),
  S("DigitalOcean", "productivity"),
  S("AWS", "productivity"),
  S("Google Cloud", "productivity"),
  S("Azure", "productivity"),
  S("Supabase", "productivity"),
  S("Firebase", "productivity"),
  S("PlanetScale", "productivity"),
  S("Neon", "productivity"),
  S("Upstash", "productivity"),
  S("MongoDB Atlas", "productivity"),
  S("Redis Cloud", "productivity"),
  S("Convex", "productivity"),
  S("Docker", "productivity"),
  S("Kubernetes", "productivity"),
  S("Terraform Cloud", "productivity"),
  S("Postman", "productivity"),
  S("Insomnia", "productivity"),
  S("Sentry", "productivity"),
  S("Datadog", "productivity"),
  S("New Relic", "productivity"),
  S("Grafana Cloud", "productivity"),
  S("PagerDuty", "productivity"),
  S("CircleCI", "productivity"),
  S("Travis CI", "productivity"),
  S("Codecov", "productivity"),
  S("Snyk", "productivity"),
  S("Auth0", "productivity"),
  S("Clerk", "productivity"),
  S("Resend", "productivity"),
  S("PostHog", "productivity"),
  S("Mixpanel", "productivity"),
  S("Hotjar", "productivity"),
  S("Cursor", "productivity"),
  S("Replit", "productivity"),
  S("Prisma", "productivity"),
  S("Cloudinary", "productivity"),
  S("Nginx", "productivity"),
  S("Stack Overflow Teams", "productivity"),

  // ── Productivity: AI Tools ────────────────────────────────
  S("ChatGPT Plus", "productivity"),
  S("Claude Pro", "productivity"),
  S("Perplexity Pro", "productivity"),
  S("Midjourney", "productivity"),
  S("Jasper AI", "productivity"),
  S("Copy.ai", "productivity"),
  S("Grammarly", "productivity"),

  // ── Productivity: Design ──────────────────────────────────
  S("Figma", "productivity"),
  S("Adobe Creative Cloud", "productivity"),
  S("Adobe Photoshop", "productivity"),
  S("Adobe Illustrator", "productivity"),
  S("Adobe Premiere Pro", "productivity"),
  S("Adobe After Effects", "productivity"),
  S("Adobe Lightroom", "productivity"),
  S("Adobe XD", "productivity"),
  S("Canva Pro", "productivity"),
  S("Sketch", "productivity"),
  S("Framer", "productivity"),
  S("Webflow", "productivity"),
  S("Miro", "productivity"),
  S("Loom", "productivity"),
  S("DaVinci Resolve", "productivity"),
  S("Procreate", "productivity"),

  // ── Productivity: Collaboration & Office ──────────────────
  S("Notion", "productivity"),
  S("Obsidian Sync", "productivity"),
  S("Coda", "productivity"),
  S("Slack", "productivity"),
  S("Zoom", "productivity"),
  S("Microsoft 365", "productivity"),
  S("Microsoft Teams", "productivity"),
  S("Google Workspace", "productivity"),
  S("Google Meet", "productivity"),
  S("Google Drive", "productivity"),
  S("Google Photos", "productivity"),
  S("Dropbox", "productivity"),
  S("OneDrive", "productivity"),
  S("Box", "productivity"),
  S("Evernote", "productivity"),
  S("Todoist Pro", "productivity"),
  S("TickTick", "productivity"),
  S("Linear", "productivity"),
  S("Asana", "productivity"),
  S("Trello", "productivity"),
  S("Jira", "productivity"),
  S("Confluence", "productivity"),
  S("ClickUp", "productivity"),
  S("Basecamp", "productivity"),
  S("Monday.com", "productivity"),
  S("Airtable", "productivity"),
  S("Calendly", "productivity"),
  S("Webex", "productivity"),
  S("GoToMeeting", "productivity"),
  S("Setapp", "productivity"),

  // ── Productivity: Marketing & Sales ───────────────────────
  S("Mailchimp", "productivity"),
  S("HubSpot", "productivity"),
  S("Salesforce", "productivity"),
  S("Stripe", "productivity"),
  S("Shopify", "productivity"),
  S("Squarespace", "productivity"),
  S("Wix", "productivity"),
  S("WordPress", "productivity"),
  S("Ghost", "productivity"),
  S("Buffer", "productivity"),
  S("Hootsuite", "productivity"),
  S("SEMrush", "productivity"),
  S("Ahrefs", "productivity"),
  S("Google Analytics", "productivity"),

  // ── Productivity: Automation ──────────────────────────────
  S("Zapier", "productivity"),
  S("IFTTT", "productivity"),
  S("Make", "productivity"),

  // ── Productivity: Customer Support ────────────────────────
  S("Intercom", "productivity"),
  S("Zendesk", "productivity"),
  S("Freshdesk", "productivity"),

  // ── Utilities: Cloud Storage ──────────────────────────────
  S("iCloud+", "utilities"),
  S("Google One", "utilities"),
  S("MEGA", "utilities"),
  S("WeTransfer", "utilities"),
  S("Proton Drive", "utilities"),

  // ── Utilities: Password Managers ──────────────────────────
  S("1Password", "utilities"),
  S("Bitwarden", "utilities"),
  S("LastPass", "utilities"),
  S("Dashlane", "utilities"),
  S("Keeper", "utilities"),
  S("NordPass", "utilities"),

  // ── Utilities: VPN & Privacy ──────────────────────────────
  S("NordVPN", "utilities"),
  S("ExpressVPN", "utilities"),
  S("Surfshark", "utilities"),
  S("ProtonVPN", "utilities"),
  S("Mullvad VPN", "utilities"),
  S("Private Internet Access", "utilities"),
  S("Windscribe", "utilities"),
  S("TunnelBear", "utilities"),

  // ── Utilities: Email & Communication ──────────────────────
  S("Proton Mail", "utilities"),
  S("Fastmail", "utilities"),
  S("Tuta Mail", "utilities"),
  S("HEY", "utilities"),

  // ── Utilities: Security ───────────────────────────────────
  S("Norton 360", "utilities"),
  S("McAfee", "utilities"),
  S("Kaspersky", "utilities"),
  S("Bitdefender", "utilities"),
  S("Malwarebytes", "utilities"),
  S("Avast", "utilities"),

  // ── Utilities: Infrastructure ─────────────────────────────
  S("Backblaze", "utilities"),
  S("Cloudflare", "utilities"),
  S("Namecheap", "utilities"),
  S("Twilio", "utilities"),
  S("Starlink", "utilities"),
  S("Tailscale", "utilities"),

  // ── Utilities: Smart Home ─────────────────────────────────
  S("Ring Protect", "utilities"),
  S("Wyze Cam Plus", "utilities"),
  S("Philips Hue", "utilities"),
  S("Sonos", "utilities"),

  // ── Health & Fitness ──────────────────────────────────────
  S("Headspace", "health"),
  S("Calm", "health"),
  S("Strava", "health"),
  S("Peloton", "health"),
  S("MyFitnessPal", "health"),
  S("Fitbit Premium", "health"),
  S("BetterHelp", "health"),
  S("Noom", "health"),
  S("Nike Training Club", "health"),
  S("Apple Fitness+", "health"),
  S("Whoop", "health"),
  S("Oura", "health"),

  // ── Education & Learning ──────────────────────────────────
  S("Duolingo Super", "other"),
  S("Coursera Plus", "other"),
  S("Udemy", "other"),
  S("Skillshare", "other"),
  S("MasterClass", "other"),
  S("Pluralsight", "other"),
  S("Codecademy Pro", "other"),
  S("LinkedIn Learning", "other"),
  S("Brilliant", "other"),
  S("Blinkist", "other"),

  // ── News & Reading ────────────────────────────────────────
  S("Medium", "other"),
  S("The New York Times", "other"),
  S("The Washington Post", "other"),
  S("The Wall Street Journal", "other"),
  S("The Economist", "other"),
  S("Bloomberg", "other"),
  S("The Athletic", "other"),
  S("Apple News+", "other"),
  S("Kindle Unlimited", "other"),

  // ── Lifestyle & Food Delivery ─────────────────────────────
  S("Amazon Prime", "other"),
  S("DoorDash DashPass", "other"),
  S("Uber One", "other"),
  S("Uber Eats Pass", "other"),
  S("Instacart+", "other"),
  S("Costco Membership", "other"),
  S("Walmart+", "other"),
  S("LinkedIn Premium", "other"),

  // ── Finance ───────────────────────────────────────────────
  S("YNAB", "other"),
  S("Robinhood Gold", "other"),
  S("Coinbase One", "other"),
  S("Copilot Money", "other"),
  S("PayPal", "other"),
  S("Wise", "other"),
  S("Revolut", "other"),

  // ── Communication ─────────────────────────────────────────
  S("WhatsApp Business", "other"),
  S("Telegram Premium", "other"),
  S("Signal", "other"),

  // ── Dating ────────────────────────────────────────────────
  S("Tinder", "other"),
  S("Bumble", "other"),
  S("Hinge", "other"),
  S("OkCupid", "other"),

  // ── Creator & Fundraising ─────────────────────────────────
  S("Ko-fi", "other"),
  S("Buy Me a Coffee", "other"),
  S("Kickstarter", "other"),
  S("GoFundMe", "other"),
].sort((a, b) => a.name.localeCompare(b.name));
