import type { SuggestionSeed } from "./types";

export const ENTERTAINMENT_SUGGESTION_SEEDS: SuggestionSeed[] = [
  ["Netflix", "netflix", "entertainment"],
  ["Spotify", "spotify", "entertainment"],
  ["YouTube Premium", "youtube", "entertainment"],
  ["Disney+", "disneyplus", "entertainment"],
  ["Prime Video", "primevideo", "entertainment"],
  ["Hulu", "hulu", "entertainment"],
  ["Max", "max", "entertainment"],
  ["Paramount+", "paramountplus", "entertainment"],
  ["Peacock", "peacock", "entertainment"],
  ["Apple TV+", "appletv", "entertainment"],
  ["Apple Music", "applemusic", "entertainment"],
  ["Tidal", "tidal", "entertainment"],
  ["SoundCloud Go+", "soundcloud", "entertainment"],
  ["Crunchyroll", "crunchyroll", "entertainment"],
  ["Audible", "audible", "entertainment"],
  ["SiriusXM", "siriusxm", "entertainment"],
  ["Deezer", "deezer", "entertainment"],
  ["Pandora", "pandora", "entertainment"],
  ["Qobuz", "qobuz", "entertainment"],
  ["MUBI", "mubi", "entertainment"],
  ["Canal+", "canalplus", "entertainment"],
  ["Vimeo", "vimeo", "entertainment"],
  ["Plex", "plex", "entertainment"],
  ["Bandcamp", "bandcamp", "entertainment"],
  ["Dailymotion", "dailymotion", "entertainment"],
  ["TuneIn", "tunein", "entertainment"],
  ["Pocket Casts", "pocketcasts", "entertainment"],
  ["Roku", "roku", "entertainment"],
  ["Kodi", "kodi", "entertainment"],
  ["Letterboxd", "letterboxd", "entertainment"],
  ["Steam", "steam", "entertainment"],
  ["PlayStation Plus", "playstation", "entertainment"],
  ["Xbox Game Pass", "xbox", "entertainment"],
  ["Nintendo Switch Online", "nintendo", "entertainment"],
  ["EA Play", "ea", "entertainment"],
  ["Ubisoft+", "ubisoft", "entertainment"],
  ["Epic Games", "epicgames", "entertainment"],
  ["Twitch", "twitch", "entertainment"],
  ["MasterClass", "masterclass", "entertainment"],
  ["Skillshare", "skillshare", "entertainment"],
  ["Curiosity Stream", "curiositystream", "entertainment"],
  ["Nebula", "nebula", "entertainment"],
  ["AMC+", "amc", "entertainment"],
  ["Shudder", "shudder", "entertainment"],
  ["Acorn TV", "acornstv", "entertainment"],
  ["Discovery+", "discoveryplus", "entertainment"],
  ["MGM+", "mgm", "entertainment"],
  ["DAZN", "dazn", "entertainment"],
  ["Fubo", "fubo", "entertainment"],
  ["Sling TV", "slingtv", "entertainment"],
  ["MLB TV", "mlb", "entertainment"],
  ["NBA League Pass", "nba", "entertainment"],
  ["NFL+", "nfl", "entertainment"],
  ["Hotstar", "hotstar", "entertainment"],
];
