import type { SuggestionSeed } from "./types";

export const HEALTH_SUGGESTION_SEEDS: SuggestionSeed[] = [
  ["Headspace", "headspace", "health"],
  ["Calm", "calm", "health"],
  ["Strava", "strava", "health"],
  ["MyFitnessPal", "myfitnesspal", "health"],
  ["Fitbit Premium", "fitbit", "health"],
  ["Garmin Connect+", "garmin", "health"],
  ["Peloton", "peloton", "health"],
  ["Nike Run Club", "nike", "health"],
  ["Adidas Running", "adidas", "health"],
  ["Noom", "noom", "health"],
  ["BetterHelp", "betterhelp", "health"],
  ["Talkspace", "talkspace", "health"],
  ["Teladoc", "teladoc", "health"],
  ["HealthifyMe", "healthifyme", "health"],
  ["Flo", "flo", "health"],
  ["Clue", "clue", "health"],
  ["Sleep Cycle", "sleepcycle", "health"],
  ["Eight Sleep", "eightsleep", "health"],
  ["WHOOP", "whoop", "health"],
  ["Oura", "oura", "health"],
  ["Centr", "centr", "health"],
  ["Aaptiv", "aaptiv", "health"],
  ["Future", "future", "health"],
  ["Lifesum", "lifesum", "health"],
  ["Cronometer", "cronometer", "health"],
  ["Freeletics", "freeletics", "health"],
  ["Fitbod", "fitbod", "health"],
  ["Down Dog", "downdog", "health"],
  ["Simple Habit", "simplehabit", "health"],
  ["Sanvello", "sanvello", "health"],
  ["ClassPass", "classpass", "health"],
  ["Mindbody", "mindbody", "health"],
  ["Trainerize", "trainerize", "health"],
  ["Zocdoc", "zocdoc", "health"],
  ["Doctolib", "doctolib", "health"],
  ["K Health", "khealth", "health"],
  ["Cerebral", "cerebral", "health"],
];
