import type { SuggestionSeed } from "./types";

export const OTHER_SUGGESTION_SEEDS: SuggestionSeed[] = [
  ["LinkedIn Premium", "linkedin", "other"],
  ["X Premium", "x", "other"],
  ["Reddit Premium", "reddit", "other"],
  ["Discord Nitro", "discord", "other"],
  ["Telegram Premium", "telegram", "other"],
  ["Snapchat+", "snapchat", "other"],
  ["Duolingo Super", "duolingo", "other"],
  ["Coursera Plus", "coursera", "other"],
  ["Udemy Personal Plan", "udemy", "other"],
  ["edX", "edx", "other"],
  ["Brilliant", "brilliant", "other"],
  ["Khan Academy", "khanacademy", "other"],
  ["Substack", "substack", "other"],
  ["Patreon", "patreon", "other"],
  ["Medium", "medium", "other"],
  ["The New York Times", "newyorktimes", "other"],
  ["The Wall Street Journal", "wsj", "other"],
  ["The Washington Post", "washingtonpost", "other"],
  ["The Guardian", "theguardian", "other"],
  ["Financial Times", "financialtimes", "other"],
  ["The Economist", "theeconomist", "other"],
  ["Bloomberg", "bloomberg", "other"],
  ["Pocket", "pocket", "other"],
  ["Instapaper", "instapaper", "other"],
  ["Raindrop.io", "raindropdotio", "other"],
  ["Feedly", "feedly", "other"],
  ["Readwise", "readwise", "other"],
  ["Amazon Prime", "amazonprime", "other"],
  ["Costco", "costco", "other"],
  ["Walmart+", "walmart", "other"],
  ["Target Circle 360", "target", "other"],
  ["Instacart+", "instacart", "other"],
  ["DoorDash DashPass", "doordash", "other"],
  ["Uber One", "uber", "other"],
  ["Lyft Pink", "lyft", "other"],
  ["Swiggy One", "swiggy", "other"],
  ["Zomato Gold", "zomato", "other"],
  ["Deliveroo Plus", "deliveroo", "other"],
  ["Just Eat Plus", "justeat", "other"],
  ["Grubhub+", "grubhub", "other"],
  ["HelloFresh", "hellofresh", "other"],
  ["Blue Apron", "blueapron", "other"],
  ["Revolut Metal", "revolut", "other"],
  ["N26 You", "n26", "other"],
  ["Monzo Plus", "monzo", "other"],
  ["Starling", "starlingbank", "other"],
  ["Robinhood Gold", "robinhood", "other"],
  ["TradingView", "tradingview", "other"],
  ["Coinbase One", "coinbase", "other"],
  ["Binance", "binance", "other"],
  ["Kraken", "kraken", "other"],
  ["Bybit", "bybit", "other"],
  ["OpenSea Pro", "opensea", "other"],
];
