import type { SuggestionSeed } from "./types";

export const PRODUCTIVITY_SUGGESTION_SEEDS: SuggestionSeed[] = [
  ["Notion", "notion", "productivity"],
  ["Figma", "figma", "productivity"],
  ["Canva Pro", "canva", "productivity"],
  ["Slack", "slack", "productivity"],
  ["Microsoft 365", "microsoft365", "productivity"],
  ["Google Workspace", "googleworkspace", "productivity"],
  ["Zoom", "zoom", "productivity"],
  ["Dropbox", "dropbox", "productivity"],
  ["Box", "box", "productivity"],
  ["Evernote", "evernote", "productivity"],
  ["Todoist", "todoist", "productivity"],
  ["Trello", "trello", "productivity"],
  ["Asana", "asana", "productivity"],
  ["ClickUp", "clickup", "productivity"],
  ["Monday.com", "mondaydotcom", "productivity"],
  ["Airtable", "airtable", "productivity"],
  ["Miro", "miro", "productivity"],
  ["Loom", "loom", "productivity"],
  ["Calendly", "calendly", "productivity"],
  ["Zapier", "zapier", "productivity"],
  ["Make", "make", "productivity"],
  ["Linear", "linear", "productivity"],
  ["Jira", "jira", "productivity"],
  ["Confluence", "confluence", "productivity"],
  ["GitHub", "github", "productivity"],
  ["GitLab", "gitlab", "productivity"],
  ["Bitbucket", "bitbucket", "productivity"],
  ["JetBrains", "jetbrains", "productivity"],
  ["Postman", "postman", "productivity"],
  ["Insomnia", "insomnia", "productivity"],
  ["Replit", "replit", "productivity"],
  ["CodeSandbox", "codesandbox", "productivity"],
  ["Vercel", "vercel", "productivity"],
  ["Netlify", "netlify", "productivity"],
  ["Heroku", "heroku", "productivity"],
  ["DigitalOcean", "digitalocean", "productivity"],
  ["Cloudflare", "cloudflare", "productivity"],
  ["AWS", "amazonaws", "productivity"],
  ["Google Cloud", "googlecloud", "productivity"],
  ["Azure", "microsoftazure", "productivity"],
  ["Supabase", "supabase", "productivity"],
  ["Firebase", "firebase", "productivity"],
  ["PlanetScale", "planetscale", "productivity"],
  ["Render", "render", "productivity"],
  ["Railway", "railway", "productivity"],
  ["Fly.io", "flydotio", "productivity"],
  ["Sentry", "sentry", "productivity"],
  ["Datadog", "datadog", "productivity"],
  ["New Relic", "newrelic", "productivity"],
  ["PagerDuty", "pagerduty", "productivity"],
  ["Atlassian", "atlassian", "productivity"],
  ["Intercom", "intercom", "productivity"],
  ["Zendesk", "zendesk", "productivity"],
  ["HubSpot", "hubspot", "productivity"],
  ["Salesforce", "salesforce", "productivity"],
  ["Pipedrive", "pipedrive", "productivity"],
  ["Mailchimp", "mailchimp", "productivity"],
  ["Brevo", "brevo", "productivity"],
  ["ConvertKit", "convertkit", "productivity"],
  ["Klaviyo", "klaviyo", "productivity"],
  ["ActiveCampaign", "activecampaign", "productivity"],
  ["Typeform", "typeform", "productivity"],
  ["SurveyMonkey", "surveymonkey", "productivity"],
  ["DocuSign", "docusign", "productivity"],
  ["Dropbox Sign", "dropboxsign", "productivity"],
  ["Grammarly", "grammarly", "productivity"],
  ["QuillBot", "quillbot", "productivity"],
  ["ChatGPT Plus", "openai", "productivity"],
  ["Claude Pro", "anthropic", "productivity"],
  ["Perplexity Pro", "perplexity", "productivity"],
  ["Otter", "otterai", "productivity"],
  ["Framer", "framer", "productivity"],
  ["Webflow", "webflow", "productivity"],
  ["Squarespace", "squarespace", "productivity"],
  ["Wix", "wix", "productivity"],
  ["Shopify", "shopify", "productivity"],
  ["WooCommerce", "woocommerce", "productivity"],
  ["BigCommerce", "bigcommerce", "productivity"],
  ["Stripe", "stripe", "productivity"],
  ["PayPal", "paypal", "productivity"],
  ["Square", "square", "productivity"],
  ["Wise", "wise", "productivity"],
  ["Mercury", "mercury", "productivity"],
  ["Brex", "brex", "productivity"],
  ["Ramp", "ramp", "productivity"],
  ["Xero", "xero", "productivity"],
  ["QuickBooks", "quickbooks", "productivity"],
  ["FreshBooks", "freshbooks", "productivity"],
  ["Gusto", "gusto", "productivity"],
  ["Rippling", "rippling", "productivity"],
  ["BambooHR", "bamboohr", "productivity"],
  ["Deel", "deel", "productivity"],
  ["Remote", "remote", "productivity"],
  ["Mural", "mural", "productivity"],
  ["TeamViewer", "teamviewer", "productivity"],
  ["AnyDesk", "anydesk", "productivity"],
  ["Notepad++", "notepadplusplus", "productivity"],
  ["Obsidian", "obsidian", "productivity"],
  ["Coda", "coda", "productivity"],
  ["Basecamp", "basecamp", "productivity"],
  ["Wrike", "wrike", "productivity"],
  ["Smartsheet", "smartsheet", "productivity"],
  ["Aha!", "aha", "productivity"],
  ["YouTrack", "youtrack", "productivity"],
  ["Azure DevOps", "azuredevops", "productivity"],
  ["CircleCI", "circleci", "productivity"],
  ["Travis CI", "travisci", "productivity"],
  ["Codecov", "codecov", "productivity"],
  ["SonarQube", "sonarqube", "productivity"],
  ["Snyk", "snyk", "productivity"],
  ["LaunchDarkly", "launchdarkly", "productivity"],
  ["Amplitude", "amplitude", "productivity"],
  ["Mixpanel", "mixpanel", "productivity"],
  ["Hotjar", "hotjar", "productivity"],
  ["FullStory", "fullstory", "productivity"],
  ["Segment", "segment", "productivity"],
  ["Algolia", "algolia", "productivity"],
  ["Contentful", "contentful", "productivity"],
  ["Sanity", "sanity", "productivity"],
  ["Storyblok", "storyblok", "productivity"],
  ["Prismic", "prismic", "productivity"],
  ["Ghost", "ghost", "productivity"],
];
