import type { SuggestionSeed } from "./types";

export const UTILITIES_SUGGESTION_SEEDS: SuggestionSeed[] = [
  ["iCloud+", "icloud", "utilities"],
  ["Google Drive", "googledrive", "utilities"],
  ["Google One", "googleone", "utilities"],
  ["Proton Mail", "protonmail", "utilities"],
  ["Proton Drive", "protondrive", "utilities"],
  ["Proton VPN", "protonvpn", "utilities"],
  ["1Password", "1password", "utilities"],
  ["LastPass", "lastpass", "utilities"],
  ["Bitwarden", "bitwarden", "utilities"],
  ["Dashlane", "dashlane", "utilities"],
  ["NordVPN", "nordvpn", "utilities"],
  ["ExpressVPN", "expressvpn", "utilities"],
  ["Surfshark", "surfshark", "utilities"],
  ["Mullvad", "mullvad", "utilities"],
  ["Windscribe", "windscribe", "utilities"],
  ["AdGuard", "adguard", "utilities"],
  ["Backblaze", "backblaze", "utilities"],
  ["Acronis", "acronis", "utilities"],
  ["Carbonite", "carbonite", "utilities"],
  ["CrashPlan", "crashplan", "utilities"],
  ["RescueTime", "rescuetime", "utilities"],
  ["IFTTT", "ifttt", "utilities"],
  ["Home Assistant Cloud", "homeassistant", "utilities"],
  ["Philips Hue", "philipshue", "utilities"],
  ["Ring Protect", "ring", "utilities"],
  ["Arlo Secure", "arlo", "utilities"],
  ["Ecobee", "ecobee", "utilities"],
  ["Tailscale", "tailscale", "utilities"],
  ["OpenVPN", "openvpn", "utilities"],
  ["Synology C2", "synology", "utilities"],
  ["QNAP", "qnap", "utilities"],
  ["MongoDB Atlas", "mongodb", "utilities"],
  ["Redis Cloud", "redis", "utilities"],
  ["Elastic Cloud", "elastic", "utilities"],
  ["Twilio", "twilio", "utilities"],
  ["Vonage", "vonage", "utilities"],
  ["OpenPhone", "openphone", "utilities"],
  ["Namecheap", "namecheap", "utilities"],
  ["GoDaddy", "godaddy", "utilities"],
  ["Cloudways", "cloudways", "utilities"],
  ["cPanel", "cpanel", "utilities"],
  ["Porkbun", "porkbun", "utilities"],
  ["SendGrid", "sendgrid", "utilities"],
  ["Mailgun", "mailgun", "utilities"],
  ["Postmark", "postmark", "utilities"],
  ["Resend", "resend", "utilities"],
  ["Auth0", "auth0", "utilities"],
  ["Okta", "okta", "utilities"],
  ["OneLogin", "onelogin", "utilities"],
  ["Keeper", "keeper", "utilities"],
  ["Fastly", "fastly", "utilities"],
  ["Akamai", "akamai", "utilities"],
  ["Bunny CDN", "bunny", "utilities"],
  ["Cloudinary", "cloudinary", "utilities"],
  ["Imgix", "imgix", "utilities"],
  ["Mapbox", "mapbox", "utilities"],
  ["HERE", "here", "utilities"],
  ["Intercom Fin", "intercom", "utilities"],
  ["Statuspage", "statuspage", "utilities"],
  ["UptimeRobot", "uptimerobot", "utilities"],
  ["Pingdom", "pingdom", "utilities"],
  ["Better Stack", "betterstack", "utilities"],
];
